CREATE TABLE IF NOT EXISTS Production.Product (
    ProductID NUMBER NOT NULL,
    Name VARCHAR(50) NOT NULL,
    ProductNumber VARCHAR(25) NOT NULL,
    MakeFlag BOOLEAN NOT NULL,
    FinishedGoodsFlag BOOLEAN NOT NULL,
    Color VARCHAR(15),
    SafetyStockLevel NUMBER NOT NULL,
    ReorderPoint NUMBER NOT NULL,
    StandardCost NUMBER(19,4) NOT NULL,
    ListPrice NUMBER(19,4) NOT NULL,
    Size VARCHAR(5),
    SizeUnitMeasureCode VARCHAR(3),
    WeightUnitMeasureCode VARCHAR(3),
    Weight NUMBER(8,2),
    DaysToManufacture NUMBER NOT NULL,
    ProductLine VARCHAR(2),
    Class VARCHAR(2),
    Style VARCHAR(2),
    ProductSubcategoryID NUMBER,
    ProductModelID NUMBER,
    SellStartDate TIMESTAMP_NTZ NOT NULL,
    SellEndDate TIMESTAMP_NTZ,
    DiscontinuedDate TIMESTAMP_NTZ,
    rowguid VARCHAR(36) NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (ProductID)
);
