CREATE TABLE IF NOT EXISTS Sales.SalesOrderHeader (
    SalesOrderID NUMBER NOT NULL,
    RevisionNumber NUMBER NOT NULL,
    OrderDate TIMESTAMP_NTZ NOT NULL,
    DueDate TIMESTAMP_NTZ NOT NULL,
    ShipDate TIMESTAMP_NTZ,
    Status NUMBER NOT NULL,
    OnlineOrderFlag BOOLEAN NOT NULL,
    SalesOrderNumber VARCHAR(25) NOT NULL,
    PurchaseOrderNumber VARCHAR(25),
    AccountNumber VARCHAR(15),
    CustomerID NUMBER NOT NULL,
    SalesPersonID NUMBER,
    TerritoryID NUMBER,
    BillToAddressID NUMBER NOT NULL,
    ShipToAddressID NUMBER NOT NULL,
    ShipMethodID NUMBER NOT NULL,
    CreditCardID NUMBER,
    CreditCardApprovalCode VARCHAR(15),
    CurrencyRateID NUMBER,
    SubTotal NUMBER(19,4) NOT NULL,
    TaxAmt NUMBER(19,4) NOT NULL,
    Freight NUMBER(19,4) NOT NULL,
    TotalDue NUMBER(19,4) NOT NULL,
    Comment VARCHAR(128),
    rowguid VARCHAR(36) NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (SalesOrderID)
);
